### ISSUE TITLE
Retry catalogue.dataspace.copernicus.eu 500 requests

### ISSUE THREAD

**Issue by EmileSonneveld** [Open-EO/openeo-opensearch-client#19]
This request sometimes returns a 500 error code with a non-empty body. The request after that returns correctly, after 30+seconds
https://catalogue.dataspace.copernicus.eu/resto/api/collections/Sentinel1/search.json?box=3.0997828000192973%2C51.26965836582776%2C3.300653013886967%2C51.3703413670677&sortParam=startDate&sortOrder=ascending&page=1&maxRecords=100&status=0%7C34%7C37&dataset=ESA-DATASET&processingLevel=LEVEL1&sensorMode=IW&productType=GRD&startDate=2020-06-06T00%3A00%3A00Z&completionDate=2020-06-06T23%3A59%3A59.999999999Z&productType=GRD

Probably this request may be retried. But first, the body of the failing request needs to be checked.

**Comment by jdries** [comment]
@EmileSonneveld  didn't we solve this now?

**Comment by EmileSonneveld** [comment]
Yes! This commit should have solved it: https://github.com/Open-EO/openeo-opensearch-client/commit/ab01de9ece1cb7bb30e0a28c5aa3b5c9db10703a
